### ISSUE TITLE
First vactual after TMC power-on is different than the rest

### ISSUE THREAD

**Issue by ondrasy** [Chr157i4n/TMC2209_Raspberry_Pi#49]
**Describe the bug**
After the TMC driver has been turned on, the first call to set_vactual_rpm() produces a different (lower) vactual value than all the other next calls.

**To Reproduce**
1. power on the TMC2209 driver
2. run the attached file stepper_test1.py several times

**Expected behavior**
Even the first call produces the same correct speed.

**Versions**
- Raspberry Pi 4
- OS Version 12-bookworm
- Version of this library 0.4.1
- TMC2209 version and manufacturer BigTreeTech TMC2209 v1.2

[console_output.txt](https://github.com/Chr157i4n/TMC2209_Raspberry_Pi/files/14129947/console_output.txt)
[stepper_test1.py.txt](https://github.com/Chr157i4n/TMC2209_Raspberry_Pi/files/14129948/stepper_test1.py.txt)

**Comment by Chr157i4n** [comment]
Hey,
thanks for the detailed bug report with the log 👍.
This bug should be fixed in the dev branch.
The calculation of the new steps_per_rev value after changing msres was missing and you changed the microstepping resolution from 2 to 32.
