### ISSUE TITLE
Request: Replace logger print-statement with python logging library

### ISSUE THREAD

**Issue by SiboVG** [Chr157i4n/TMC2209_Raspberry_Pi#54]
Currently, logger message are just printed to the console. However, I believe it would be better to replace this with the `logging` library, as it offers more flexibility of where the log messages can be written to.

**Comment by Chr157i4n** [comment]
I have to think about how i want to approach this. Either we switch from my own logger class to python-```logging``` completely. or we integrate python-```logging``` into the current logger class.
i don't have time this week, so it will probably take a little longer, or you could implement it and make a Pull request.

**Comment by SiboVG** [comment]
> I have to think about how i want to approach this. Either we switch from my own logger class to python-`logging` completely. or we integrate python-`logging` into the current logger class. i don't have time this week, so it will probably take a little longer, or you could implement it and make a Pull request.

Sure, I'll take a look at it. I'm also not sure which strategy would be best. It will probably become clear during development. Ideally, I'd want to maintain compatibility with previous versions so the function calls remain the same. We'll see, I'll keep you updated!

**Comment by SiboVG** [comment]
Fixed by #55.
