### ISSUE TITLE
Direction change without using UART

### ISSUE THREAD

**Issue by sin-2pi** [Chr157i4n/TMC2209_Raspberry_Pi#71]
I am attempting to use the function to set the motor direction either CW or CCW. When I attempt to use the function it wants to connect with UART and I am not using that. 

Is there a different way to change motor direction? Can I use negative steps?

**Comment by Chr157i4n** [comment]
**just as sidenote:**
there are two functions to set the direction:
`set_direction_reg()` this sets the direction by changing the register via UART
`set_direction_pin()` this sets the direction by switching the DIR gpio pin

**The Answer to you question:**
The run_to_position function internally switches direction.
So you even have to use negative values for the target position
