### ISSUE TITLE
Return of driver's test_uart function always true?

### ISSUE THREAD

**Issue by Henrikb8** [Chr157i4n/TMC2209_Raspberry_Pi#85]
This is my first issue, so bear with me please :) 
In the _TMC_2209_test.py there is the function to check if the driver has a uart connection right? But if the connection does not work, it still returns true (line 149). Shoudn't be the status returned instead?

Thank you for your reply!

**Comment by Chr157i4n** [comment]
Hey,

I have always used the function manually and looked at the print output. But you're right, returning the status probably makes more sense.

**Comment by Henrikb8** [comment]
Ah okay, i see. Thanks for your reply and taking my suggestion into account :)
